### ISSUE TITLE
The "wait for url|path to match ..." step is broken

### ISSUE THREAD

**Issue by pabrown1975** [jambit/wdio-cucumber-selected-steps#6]
The regular expression for this step is (_lib/steps/delay.js, line 16_):
`/^I wait(?: (\d+)ms) for the (url|path) to( not)? (contain|match) "([^"]+)"$/`

This will not match correctly if the "ms" parameter is not specified.  I think it needs a question mark after the `(?: (\d+)ms)`, not sure.

**Comment by SantoJambit** [comment]
Sorry for the late reply. I did not get notified about this issue.

Not sure why my state for "watch" has not been active. I would have thought this happens on creation of the repository.

Anyway, about your issue: I actually noticed this myself and fixed it here: https://github.com/jambit/wdio-cucumber-selected-steps/commit/57bd6bb0d54ed59060cbe19c36e5cb8a5616f739

You're right, that a question mark has been missing. The latest release contains the fix.
